package application;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Roselyn
 */
public class MaxNote extends javax.swing.JPanel {

    public javax.swing.JPanel maxnotePanel;
    /**
     *
     * @return
     */
    public javax.swing.JPanel getMaxNotePanel() {
    return maxnotePanel;
}
    
    /**
     * Creates new form MaxNote
     */
    public MaxNote() {
        initComponents();
    }

    private void addNoteToHolder(String title, String text) {
    JPanel noteSummaryPanel = new JPanel();
    noteSummaryPanel.setLayout(new BorderLayout());
    JLabel titleLabel = new JLabel(title);
    JLabel textLabel = new JLabel(text.length() > 30 ? text.substring(0, 30) + "..." : text); // Shorten text
    noteSummaryPanel.add(titleLabel, BorderLayout.NORTH);
    noteSummaryPanel.add(textLabel, BorderLayout.CENTER);

    noteSummaryPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    noteSummaryPanel.setPreferredSize(new Dimension(200, 100));

    noteSummaryPanel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            titleField.setText(title);
            NotePanel1.setVisible(true);
        }
    });

    NoteHolder.add(noteSummaryPanel);
    NoteHolder.revalidate();
    NoteHolder.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        titleField = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        jPanel1.setBackground(new java.awt.Color(255, 245, 228));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables

    JPanel getMaxNotePanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
