/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project;

/**
 *
 * @author Roselyn
 */
public class SaveNote extends javax.swing.JPanel {

    /**
     * Creates new form SaveNote
     */
    public SaveNote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveItemHolder = new java.awt.Panel();
        SaveNote = new javax.swing.JLabel();

        SaveNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Save.png"))); // NOI18N

        javax.swing.GroupLayout SaveItemHolderLayout = new javax.swing.GroupLayout(SaveItemHolder);
        SaveItemHolder.setLayout(SaveItemHolderLayout);
        SaveItemHolderLayout.setHorizontalGroup(
            SaveItemHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveItemHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaveItemHolderLayout.setVerticalGroup(
            SaveItemHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaveItemHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaveItemHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaveItemHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel SaveItemHolder;
    private javax.swing.JLabel SaveNote;
    // End of variables declaration//GEN-END:variables
}
